version: "3.9"

services:
  postgres:
    container_name: ecomm
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: new_password
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data # Correct path for PostgreSQL data

volumes:
  db:
